# Generated by Django 5.1.6 on 2025-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_course_alter_lesson_preview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
