# Generated by Django 5.1.6 on 2025-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_payment_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
