# Generated by Django 5.1.6 on 2025-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0010_remove_payment_payment_method_alter_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
