# Generated by Django 5.1.6 on 2025-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0012_remove_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Цена"),
        ),
    ]
