# Generated by Django 5.1.6 on 2025-03-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0014_remove_course_price_remove_course_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Цена"),
        ),
    ]
