# Generated by Django 5.1.6 on 2025-03-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0015_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("stripe", "Stripe")],
                max_length=10,
                null=True,
            ),
        ),
    ]
