# Generated by Django 5.1.6 on 2025-03-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0016_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
